name: C/C++ CI

on:  #[push]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        submodules: true
    - name: List submodule files
      run: |
        ls -la
        echo -e "\n\n\n"
        echo -e "Submodule files"
        ls -la ./modules
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.apt-cache
        key: ${{ runner.os }}-apt-${{ hashFiles('**/cicd.yml') }}
    - name: install dependencies
      run: |
        sudo apt-get update --download-only -o dir::cache::archives="${{ steps.cache-deps.outputs.cache-hit != 'true' && '~/.apt-cache' || '' }}"
        sudo apt-get install -y gcc-arm-none-eabi cmake gdb-multiarch qemu-system-arm
    - name: configure
      run: cmake --preset arm-cortex-m0-unix
    - name: build
      run: cmake --build --preset arm-cortex-m0-unix